---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-addons-cluster-x-k8s-io-v1alpha1-kubewardenaddon
  failurePolicy: Fail
  name: mkubewardenaddon.kb.io
  rules:
  - apiGroups:
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubewardenaddons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-addon-cluster-x-k8s-io-v1alpha1-kubewardenpolicy
  failurePolicy: Fail
  name: mkubewardenpolicy.kb.io
  rules:
  - apiGroups:
    - addon.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubewardenpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-addons-cluster-x-k8s-io-v1alpha1-kubewardenaddon
  failurePolicy: Fail
  name: vkubewardenaddon.kb.io
  rules:
  - apiGroups:
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubewardenaddons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-addon-cluster-x-k8s-io-v1alpha1-kubewardenpolicy
  failurePolicy: Fail
  name: vkubewardenpolicy.kb.io
  rules:
  - apiGroups:
    - addon.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubewardenpolicies
  sideEffects: None
